### ISSUE TITLE
Publish Initial Version to NPM

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/scsb-rest-client#2]
This Client will be used by other services and should be trackable/usable via NPM with version control. 💃

**Comment by nodanaonlyzuul** [comment]
This is up [in npm now](https://www.npmjs.com/package/@nypl/scsb-rest-client).
I don't mind using github to bring in node modules - but hey - that's just me.

I'm going to make a documentation change in README to change the "With Github" section to use https, and not git as the scheme - because I KNOW https would work on servers and EB machines won't use the git scheme without additional documentation.
